### ISSUE TITLE
mouse buttons occasionally wont register.

### ISSUE THREAD

**Issue by Donthobaso** [CemuUser8/mouse2joystick_custom_CEMU#18]
about 20% of my mouse inputs wont register and thus can lead to losing game focus by clicking on desktop for example, or it can lead to button release not being activated.

but its the losing focus part that impacts the most due to loss off performance when game isnt in foreground, i did i 'fix' for myself by making a script that tabs into the game if it loses focus.

i havent tested much regarding increasing the scripts priority in Task manager but from the little i have tested it seems to improve quite a bit. 
but manually setting the priority to max each time the script is started is a bit anoyying.

[settings.ini.txt](https://github.com/CemuUser8/mouse2joystick_custom_CEMU/files/4742507/settings.ini.txt)

**Comment by CemuUser8** [comment]
I have not seen this behavior myself, and looking at your settings the only thing I can think to try changing would be the Mouse Check Frequency. You have it set to "1" which means it is trying to check the mouse location every 1ms ( it isn't actually that fast due to OS restrictions ) which may have a side effect of losing mouse clicks, doesn't really make sense but is a possibility. I now recommend using something around 75, as it gives the mouse time to move and reach max joystick motion while still felling responsive.

Also you could try running the script as an admin if you don't already, it may help.

Lastly make sure any driver level mouse macros are not running, Older version of Synapse for Razer caused interference, not sure if it is still a problem but something to look out for.

Let me know if you have any luck with those modifications.

**Comment by Donthobaso** [comment]
so i tested setting to 75 and it fixed it, though i don't personally like the camera movement but thats an acceptable loss.
fyi ive always been running in admin and i dont have synapse or anything like that.
and also the script sometimes bugs out so i cant interact with anything with my mouse and its fixed by restarting the script, im guessing its bugging out due to mouse update setting is at 1, and so far i havent gotten that bug with mouse check at 75.
thx for the help!

**Comment by CemuUser8** [comment]
Ok, thank you for checking and providing feedback.

Feel free to test different values, if 75 feels noticeably worse. Maybe start at 15, and go up by 10 until the problem goes away?
