### ISSUE TITLE
Drop fps

### ISSUE THREAD

**Issue by playtechAqua** [CemuUser8/mouse2joystick_custom_CEMU#4]
This custom mouse2joystick is really great, except that it cause cemu to drop5-8 fps on any game I play, but not while I hold down the gyro button though, which is weird, unless I do that or turn it off cemu will drop frames. Don't know how holding down the gyro control button fix it, I'm hoping you could check that.

**Comment by CemuUser8** [comment]
Holding down the gyro button temporarily disables the timer checking the mouse position, therefor it basically turns off the controller for the duration.

I've had this reported before and unfortunately I don't know how to fix it, as I've tried to optimize the best I can. If I experience any drops it is at most 1-2 fps, and that is extremely rare on my machine. Since most games I can get higher than the original fps so I usually cap what should be the default fps of the game (usually 30 or 60 depending on the game). I test on a i7 3770K @ 4.8GHz with 16GB of RAM, running both CEMU and game files (script too) on a SSD.

One thing you can try is lowering the priority of the script, as it doesn't need to be normal even, maybe I can make it change itself, if you report that it helps. Another user said that the fall Windows creators update helped, but I think that is because the update helps prioritize running background processes (especially for games?)

Another thing that may help is increasing the mouse check frequency, but you'll start to notice a lag between starting and stopping moving the mouse if it gets too high.

I will look through and try to find out what step is causing the loss, by process of elimination. Because if an empty check at the same frequency causes the same issue then there is really nothing I can do, but if it is slowing down on a calculation I may be able to optimize more.

**Comment by playtechAqua** [comment]
Nothing works unfortunately, even using cemu and mouse2joy on an SSD. It also doesn't seems like the mouse checking is the one causing it, I try to compare between setting it to 1 and 1000 and the fps drop is the exact same. Guess I should stick with using just the keyboard for now.

**Comment by CemuUser8** [comment]
I will look into either a better alternate than the used calculations, or see if there is a way to make them process faster. I'm sorry this happens on some machines, I wish I could narrow it down faster.

**Comment by playtechAqua** [comment]
Ok, I still don't know why the lag happen, but I do know that it's not your custom mouse2joy fault, it's actually the main software fault. I tried the main branch on some other pc games and it lower the fps on those games too. Also using cemu 1.11.2 fixed the fps issue so I guess it's fine now.
